name: CI for CMXD

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  HUGO_VERSION: "0.82.0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: init page guide
        run: |
          wget -c https://github.com/gohugoio/hugo/releases/download/v${{env.HUGO_VERSION}}/hugo_${{env.HUGO_VERSION}}_Linux-64bit.tar.gz
          tar xf hugo_${{env.HUGO_VERSION}}_Linux-64bit.tar.gz
          ./hugo --environment=production
      - name: deploy page guide
        uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: ${{secrets.OSS_ENDPOINT}}
          access-key-id: ${{secrets.OSS_ID}}
          access-key-secret: ${{secrets.OSS_SECRET}}
          sts-token: ""
      - run: |
          ls -alh public/
          ossutil cp -rf public/ oss://cmxd/
      - name: Sending Build Status
        if: always()
        env:
          DINGTALK_ACCESS_TOKEN: ${{ secrets.DINGTALK_ACCESS_TOKEN }}
          DINGTALK_SECRET: ${{ secrets.DINGTALK_SECRET }}
          JOB_STATE: ${{ job.status }}
          RUNNER_OS: ${{ runner.os }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_WORKFLOW: ${{ env.GITHUB_WORKFLOW }}
        run: |
          python3 notify.py
